# Generated by Django 2.2.7 on 2019-12-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191206_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
