# Generated by Django 2.2.7 on 2019-12-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_subcategory_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
