# Generated by Django 2.2.7 on 2019-12-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_subcategory_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='thumbnail_url',
        ),
    ]
