# Generated by Django 2.2.7 on 2019-12-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191206_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
