# Generated by Django 2.2.7 on 2019-12-06 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191206_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='cover_img',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='thumbnail_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
