# Generated by Django 2.2.7 on 2019-12-10 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_careermail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careermail',
            name='document',
            field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='careermail',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='careermail',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
    ]
