# Generated by Django 3.0.8 on 2020-07-04 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Contact',
        ),
    ]
